# Deploy to https://opentdatach.github.io/ojp-demo-app
name: Build & Deploy to opentdatach.github.io/ojp-demo-app

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      
      - run: npm ci

      - name: Inject secrets
        run: |
          sed -i "s|PLACEHOLDER_REPLACE__PROD|${{ secrets.OJP_DEMO_APP_PROD_KEY }}|g" \
            src/app/config/app-config.ts
          sed -i "s|PLACEHOLDER_REPLACE__INT|${{ secrets.OJP_DEMO_APP_INT_KEY }}|g" \
            src/app/config/app-config.ts
          sed -i "s|PLACEHOLDER_REPLACE__TEST|${{ secrets.OJP_DEMO_APP_TEST_KEY }}|g" \
            src/app/config/app-config.ts

          sed -i "s|PLACEHOLDER_REPLACE__V2_INT|${{ secrets.OJP_DEMO_APP_V2_INT_KEY }}|g" \
            src/app/config/app-config.ts

          sed -i "s|PLACEHOLDER_REPLACE__LA_BETA|${{ secrets.OJP_DEMO_APP_LA_Beta_KEY }}|g" \
            src/app/config/app-config.ts

          sed -i "s|PLACEHOLDER_REPLACE__FARE_INT|${{ secrets.OJP_DEMO_APP_NOVA_INT_KEY }}|g" \
            src/app/config/app-config.ts

      - name: Build
        run: npm run build -- --configuration production --base-href=/ojp-demo-app/

      - name: Copy index.html to 404.html for Angular routing
        run: cp dist/ojp-demo-app/index.html dist/ojp-demo-app/404.html

      - name: Debug distribution
        run: ls -R ${{ github.workspace }}/dist || echo "dist missing!"

      - name: Deploy to target repo gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist/ojp-demo-app
          external_repository: openTdataCH/ojp-demo-app
          publish_branch: gh-pages
          personal_token: ${{ secrets.OJP_DEMO_APP_DEPLOY_TOKEN }}
          commit_message: "deploy: ${{ github.sha }}"
