name: Deploy Test

on:
  # needed for manual runs
  workflow_dispatch:
  push:
    branches:
      - deploy-test
      # works just with the branch?
      - feature/updates-github-deploy

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello from deploy-test branch"